name: Build on Ubuntu 22.04

permissions: write-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  debian:
    name: Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        swap-size-mb: 512
        remove-dotnet: 'true'
        emove-android: 'true'
          
    - name: Checkout Source
      uses: actions/checkout@v4
      
    - name: Add repository
      run: |
        sudo curl -L -o /etc/apt/trusted.gpg.d/ros1-on-ubuntu.gpg.asc https://sourceforge.net/projects/ros-for-ubuntu/files/repo/ROSMirror/public-file.key
        sudo bash -c "echo 'deb https://sourceforge.net/projects/ros-for-ubuntu/files/repo/ROSMirror jammy main' >> /etc/apt/sources.list.d/ros1-on-ubuntu.list"
        sudo apt update -y
      
    - name: Install the basic dev packages
      run: sudo apt-get install -y equivs curl git devscripts lintian build-essential automake autotools-dev cmake g++ python3-pip
        

    - name: Install Build Deps
      run: sudo mk-build-deps -i -t "apt -y" -r

    - name: Build Package
      run: |
        dpkg-buildpackage -b --root-command="sudo" -uc -us  -j4
        
    - name: Prepare Artifacts
      run: |
        mkdir -p artifacts
        mv ../*.deb artifacts

    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ROS Auto Build
        path: ${{ github.workspace }}/artifacts/*
        compression-level: 9 # maximum compression
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
